DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS stats
(
    s_id        BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT stats_pk PRIMARY KEY     NOT NULL,
    s_app       VARCHAR(250)                NOT NULL,
    s_uri       VARCHAR(2000)               NOT NULL,
    s_ip        VARCHAR(100)                NOT NULL,
    s_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
)