DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS stats
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT stats_pk PRIMARY KEY   NOT NULL,
    app       VARCHAR(250)                NOT NULL,
    uri       VARCHAR(2000)               NOT NULL,
    ip        VARCHAR(100)                NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL
)